# Generated by Django 4.2.5 on 2023-10-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="User bio or description",
                max_length=300,
                verbose_name="Description",
            ),
        ),
    ]
