# Generated by Django 4.2.4 on 2023-11-12 02:29

import apps.accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Profile image or avatar",
                null=True,
                upload_to=apps.accounts.utils.upload_to_profile_images,
                verbose_name="Profile image",
            ),
        ),
    ]
