# Generated by Django 4.2.2 on 2023-06-21 00:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_email_verified_alter_account_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the email verification token', unique=True, verbose_name='Email verification token'),
        ),
    ]
