# Generated by Django 4.2.2 on 2023-06-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, help_text='User bio or description', max_length=500, verbose_name='Description'),
        ),
    ]
