# Generated by Django 4.2.2 on 2023-06-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, help_text='Name', max_length=120, verbose_name='Name'),
        ),
    ]
