# Generated by Django 4.2.4 on 2023-09-04 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0005_remove_account_first_name_remove_account_last_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountInterfaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the account interfaces",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the interfaces were created",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the interfaces were last modified",
                        verbose_name="Date modified",
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        help_text="Account associated with the interfaces",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Interfaces",
                "verbose_name_plural": "Account Interfaces",
            },
        ),
    ]
