# Generated by Django 4.2.4 on 2023-09-18 04:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_delete_accountinterfaces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email_verification_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier for the email verification token",
                unique=True,
                verbose_name="Email verification token",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the user",
                max_length=120,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Profile image or avatar",
                null=True,
                upload_to="accounts/",
                verbose_name="Profile image",
            ),
        ),
    ]
