# Generated by Django 4.2.4 on 2023-09-18 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_account_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email_verification_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the email verification token",
                unique=True,
                verbose_name="Email verification token",
            ),
        ),
    ]
