# Generated by Django 4.2.3 on 2023-09-27 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the account settings",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
