# Generated by Django 4.2.3 on 2023-09-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_settings_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settings",
            old_name="site_updates",
            new_name="site_update_emails",
        ),
    ]
