# Generated by Django 4.2.3 on 2023-09-27 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_settings_user_settings_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_email",
                    models.BooleanField(
                        default=False,
                        help_text="Show or hide the email",
                        verbose_name="Show email",
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Receive marketing emails",
                        verbose_name="Marketing emails",
                    ),
                ),
                (
                    "weekly_digest_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Receive weekly digest emails",
                        verbose_name="Weekly digest emails",
                    ),
                ),
                (
                    "discovery_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Receive emails about new features and tips",
                        verbose_name="Discovery emails",
                    ),
                ),
                (
                    "site_update_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Receive site update emails",
                        verbose_name="Site updates",
                    ),
                ),
                (
                    "inbox_message_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications when you receive a new message                                                      in your inbox",
                        verbose_name="Inbox message notifications",
                    ),
                ),
                (
                    "announcement_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications about new announcements",
                        verbose_name="Announcement notifications",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the account settings",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the item was created modified",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the item was last modified",
                        verbose_name="Date modified",
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        help_text="Account that is connected to the settings",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Setting",
                "verbose_name_plural": "Account settings",
            },
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
