# Generated by Django 4.2.3 on 2023-09-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_accountsettings_delete_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_marked_for_deletion",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has marked their account for                                                 deletion",
                verbose_name="Is marked for deletion",
            ),
        ),
    ]
