# Generated by Django 4.2.3 on 2023-10-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_accountsettings_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountsettings",
            old_name="announcement_notifications",
            new_name="receive_announcement_notifications",
        ),
        migrations.RenameField(
            model_name="accountsettings",
            old_name="discovery_emails",
            new_name="receive_discovery_emails",
        ),
        migrations.RenameField(
            model_name="accountsettings",
            old_name="marketing_emails",
            new_name="receive_marketing_emails",
        ),
        migrations.RenameField(
            model_name="accountsettings",
            old_name="site_update_emails",
            new_name="receive_site_update_emails",
        ),
        migrations.RenameField(
            model_name="accountsettings",
            old_name="weekly_digest_emails",
            new_name="receive_weekly_digest_emails",
        ),
        migrations.RemoveField(
            model_name="accountsettings",
            name="inbox_message_notifications",
        ),
        migrations.AddField(
            model_name="accountsettings",
            name="receive_inbox_message_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Receive notifications when you receive a new                                                              message in your inbox",
                verbose_name="Inbox message notifications",
            ),
        ),
    ]
