# Generated by Django 4.2.4 on 2023-10-22 21:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the item was created modified",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the item was last modified",
                        verbose_name="Date modified",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the item was created modified",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the item was last modified",
                        verbose_name="Date modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the objective",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the objective",
                        max_length=2000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "release_status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("released", "Released"),
                            ("archived", "Archived"),
                        ],
                        default="planned",
                        help_text="Release status of the objective",
                        max_length=255,
                        verbose_name="Release status",
                    ),
                ),
                (
                    "up_votes",
                    models.IntegerField(
                        default=0,
                        help_text="Number of up votes for the objective",
                        verbose_name="Up votes",
                    ),
                ),
                (
                    "date_released",
                    models.DateTimeField(
                        blank=True,
                        help_text="Server date and time when the feature was released",
                        null=True,
                        verbose_name="Date released",
                    ),
                ),
                (
                    "date_archived",
                    models.DateTimeField(
                        blank=True,
                        help_text="Server date and time when the feature was archived",
                        null=True,
                        verbose_name="Date archived",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the article",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category of the objective",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objective",
                        to="roadmap.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objective",
                "verbose_name_plural": "Objectives",
                "ordering": ["-name", "-date_created"],
            },
        ),
    ]
