# Generated by Django 4.2.4 on 2023-10-22 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Objective",
            new_name="Feature",
        ),
        migrations.AlterModelOptions(
            name="feature",
            options={
                "ordering": ["-name", "-date_created"],
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
            },
        ),
    ]
