# Generated by Django 4.2.4 on 2023-10-23 02:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("roadmap", "0002_rename_objective_feature_alter_feature_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the category",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the category",
                max_length=500,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Name of the category", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category of the feature",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="objective",
                to="roadmap.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the feature",
                max_length=2000,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(
                help_text="Name of the feature", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="release_status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("released", "Released"),
                    ("archived", "Archived"),
                ],
                default="planned",
                help_text="Release status of the feature",
                max_length=255,
                verbose_name="Release status",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="up_votes",
            field=models.IntegerField(
                default=0,
                help_text="Number of up votes for the feature",
                verbose_name="Up votes",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the feature",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
