# Generated by Django 4.2.4 on 2023-10-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roadmap", "0003_alter_category_options_category_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="The URL slug based on the category name, slug fields should be 50 characters or                            less",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
