# Generated by Django 4.2.4 on 2023-10-23 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roadmap", "0004_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default=datetime.datetime(
                    2023, 10, 23, 2, 14, 27, 777562, tzinfo=datetime.timezone.utc
                ),
                help_text="The URL slug based on the category name, slug fields should be 50 characters or                            less",
                max_length=200,
                unique=True,
                verbose_name="Slug",
            ),
            preserve_default=False,
        ),
    ]
