# Generated by Django 4.2.4 on 2023-11-02 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("roadmap", "0005_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the item",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="up_votes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of up votes for the feature",
                verbose_name="Up votes",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the item",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
