# Generated by Django 4.2.4 on 2023-10-19 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ("name",),
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.AlterField(
            model_name="country",
            name="country_code",
            field=models.CharField(
                help_text="Code of the country (e.g., US, UK, etc.)",
                max_length=16,
                verbose_name="Country code",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.ImageField(
                help_text="Flag of the country", upload_to="flags", verbose_name="Flag"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                help_text="Name of the country", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="phone_code",
            field=models.IntegerField(
                help_text="Phone code of the country (e.g., 1, 44, etc.)",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Phone code",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="slug",
            field=models.SlugField(
                help_text="The slug based on the country name",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
