# Generated by Django 4.2.2 on 2023-06-28 23:45

from django.conf import settings
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the post', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='The URL slug based on the post title', max_length=200, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='It is recommended meta tag descriptions not to be longer than 160 characters', max_length=200, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date_modified')),
                ('date_published', models.DateTimeField(auto_now=True, verbose_name='date_modified')),
                ('authors', models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
