# Generated by Django 4.2.4 on 2023-10-17 15:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content2",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Primary content of the post using rich text editor",
                null=True,
                verbose_name="Content2",
            ),
        ),
    ]
