# Generated by Django 4.2.2 on 2023-06-28 23:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_content_remove_post_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Server date and time when the post was created', verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Server date and time when the post was last modified', verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the post', unique=True, verbose_name='UUID'),
        ),
    ]
