# Generated by Django 4.2.4 on 2023-10-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_article_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                help_text="Visibility of the article",
                max_length=55,
                verbose_name="Visibility",
            ),
        ),
    ]
