# Generated by Django 4.2.4 on 2023-10-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_article_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="number_of_revisions",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of revisions that have been made to the                                                      article",
                verbose_name="Number of revisions",
            ),
        ),
    ]
