# Generated by Django 4.2.2 on 2023-06-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_status_alter_post_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published')], default='draft', help_text='Current status of the post', max_length=55, verbose_name='Status'),
        ),
    ]
