# Generated by Django 4.2.2 on 2023-06-29 00:02

from django.db import migrations
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now, help_text='Primary content of the post using rich text editor', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
