# Generated by Django 4.2.2 on 2023-06-29 00:05

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(auto_now=True, help_text='Server date and time when the post was published', verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Primary content of the post using rich text editor', verbose_name='Content'),
        ),
    ]
