# Generated by Django 4.2.4 on 2023-11-02 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_comment_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Whether the item has been deleted or not",
                verbose_name="Is deleted",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the item",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Whether the item has been deleted or not",
                verbose_name="Is deleted",
            ),
        ),
    ]
