# Generated by Django 4.2.2 on 2023-06-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_date_published_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(blank=True, help_text='Server date and time when the post was published', null=True, verbose_name='Date published'),
        ),
    ]
