# Generated by Django 4.2.2 on 2023-06-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='The URL slug based on the post title', max_length=200, null=True, unique=True),
        ),
    ]
