# Generated by Django 4.2.2 on 2023-06-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_text_blank_and_null_post_text_blank_only_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_blank_and_null',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_blank_only',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_null_only',
        ),
    ]
