# Generated by Django 4.2.4 on 2023-08-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_post_meta_description_post_meta_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="The URL slug based on the post title, slug fields should be 50 characters or                            less",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
    ]
