# Generated by Django 4.2.4 on 2023-09-11 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0013_alter_post_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
        migrations.AddField(
            model_name="post",
            name="allow_comments",
            field=models.BooleanField(
                default=True,
                help_text="If checked, comments are allowed for this post",
                verbose_name="Allow comments",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="allow_sharing",
            field=models.BooleanField(
                default=True,
                help_text="If checked, social media sharing is allowed for this post",
                verbose_name="Allow social media sharing",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                help_text="User who created the post",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_posts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="date_deleted",
            field=models.DateTimeField(
                blank=True,
                help_text="Server date and time when the post was deleted",
                null=True,
                verbose_name="Date deleted",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted the post",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deleted_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="modified_by",
            field=models.ForeignKey(
                default=1,
                help_text="User who last modified the post",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modified_posts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="primary_author",
            field=models.ForeignKey(
                default=1,
                help_text="Primary author of the post",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_posts_as_primary",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="release_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Review"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Current status of the post",
                max_length=55,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="authors",
            field=models.ManyToManyField(
                help_text="Post authors.",
                related_name="authored_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords",
                max_length=200,
                null=True,
            ),
        ),
    ]
