# Generated by Django 4.2.4 on 2023-09-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_remove_post_status_post_allow_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the post is deleted",
                verbose_name="Is deleted",
            ),
        ),
    ]
