# Generated by Django 4.2.4 on 2023-09-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_remove_post_primary_author_post_lead_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image of the post",
                null=True,
                upload_to="blog/featured-images/",
            ),
        ),
    ]
