# Generated by Django 4.2.4 on 2023-09-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_alter_post_date_created_alter_post_date_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Server date and time when the post was created",
                verbose_name="Date created",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_deleted",
            field=models.DateTimeField(
                blank=True,
                help_text="Server date and time when the item was deleted",
                null=True,
                verbose_name="Date deleted",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_published",
            field=models.DateTimeField(
                blank=True,
                help_text="Server date and time when the item was published",
                null=True,
                verbose_name="Date published",
            ),
        ),
    ]
