# Generated by Django 4.2.4 on 2023-09-17 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0020_remove_post_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="authors",
            field=models.ManyToManyField(
                help_text="Post authors.",
                related_name="authored_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Server date and time when the item was created modified",
                verbose_name="Date created",
            ),
        ),
    ]
