# Generated by Django 4.2.4 on 2023-09-18 05:04

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0022_alter_post_meta_description_alter_post_meta_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image of the post",
                null=True,
                upload_to=apps.blog.models.upload_to_featured_images,
            ),
        ),
    ]
