# Generated by Django 4.2.4 on 2023-09-18 05:12

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0023_alter_post_featured_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image_raw",
            field=models.ImageField(
                blank=True,
                help_text="Original unedited image of the post",
                null=True,
                upload_to=apps.blog.models.upload_to_featured_images,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="featured_image_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Featured image thumbnail of the post",
                null=True,
                upload_to=apps.blog.models.upload_to_featured_images,
            ),
        ),
    ]
