# Generated by Django 4.2.3 on 2023-09-27 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0025_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have downvoted this comment",
                related_name="comment_downvotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have upvoted this comment",
                related_name="comment_upvotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent comment that this comment replied to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_comments",
                to="blog.comment",
            ),
        ),
    ]
