# Generated by Django 4.2.4 on 2023-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={
                "ordering": ("name",),
                "verbose_name": "Subscription plan",
                "verbose_name_plural": "Subscription plans",
            },
        ),
        migrations.AlterModelOptions(
            name="subscriptionterm",
            options={
                "ordering": ("pk",),
                "verbose_name": "Subscription term",
                "verbose_name_plural": "Subscription terms",
            },
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes for the staff and admins, notes are not shown to the users",
                max_length=1000,
                null=True,
                verbose_name="Admin notes",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionterm",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes for the staff and admins, notes are not shown to the users",
                max_length=1000,
                null=True,
                verbose_name="Admin notes",
            ),
        ),
    ]
