# Generated by Django 4.2.4 on 2023-11-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_alter_subscriptionplan_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscriptionterm",
            constraint=models.UniqueConstraint(
                fields=("subscription_plan", "interval"),
                name="unique_subscription_plan_interval",
            ),
        ),
    ]
