# Generated by Django 4.2.4 on 2023-11-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_subscriptionterm_unique_subscription_plan_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionterm",
            name="interval",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("annual", "Annual")],
                default="monthly",
                help_text="Billing interval for this term",
                max_length=24,
            ),
        ),
    ]
