# Generated by Django 4.2.4 on 2023-11-06 01:34

import apps.subscriptions.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0007_alter_subscriptionplan_features_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="plan_category",
            field=models.CharField(
                choices=[("standard", "Standard")],
                default="standard",
                help_text="Allows for multiple subscription plan categories (e.g.,                                     analytics plans, advertising plans, etc.)",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="features_list",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Features list, features are separated by comma (e.g.,                                          ["5 products", "Basic analytics", ...])',
                null=True,
                validators=[apps.subscriptions.validators.validate_features_list],
                verbose_name="Features list",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionterm",
            name="price_cents",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Price in cents (e.g. 1000 = $10.00)",
                null=True,
                verbose_name="Price cents",
            ),
        ),
    ]
