# Generated by Django 4.2.4 on 2023-11-06 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0009_alter_subscriptionplan_plan_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionterm",
            options={
                "ordering": ("price_cents",),
                "verbose_name": "Subscription term",
                "verbose_name_plural": "Subscription terms",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the item",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the item was created modified",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the item was last modified",
                        verbose_name="Date modified",
                    ),
                ),
                (
                    "purchase_status",
                    models.CharField(
                        choices=[
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        help_text="Purchase status",
                        max_length=50,
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True,
                        help_text="If true, the subscription will automatically renew at the end of the                                     term",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this subscription order is active",
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the subscription period started",
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when the subscription period will end",
                        null=True,
                    ),
                ),
                (
                    "date_renewal",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date the subscription will renew",
                        null=True,
                    ),
                ),
                (
                    "date_cancelled",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date the subscription was cancelled",
                        null=True,
                    ),
                ),
                (
                    "date_refunded",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date the subscription was refunded",
                        null=True,
                    ),
                ),
                (
                    "date_changed_plan",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date the subscription plan was changed",
                        null=True,
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe checkout session ID",
                        max_length=255,
                        null=True,
                        verbose_name="Stripe checkout session ID",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe product ID at the time of the order",
                        max_length=255,
                        null=True,
                        verbose_name="Stripe product ID",
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe price ID at the time of the order",
                        max_length=255,
                        null=True,
                        verbose_name="Stripe price ID",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe subscription ID at the time of the order",
                        max_length=255,
                        null=True,
                        verbose_name="Stripe subscription ID",
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes for the staff and admins, notes are not shown to the users",
                        max_length=1000,
                        null=True,
                        verbose_name="Staff notes",
                    ),
                ),
                (
                    "purchaser",
                    models.ForeignKey(
                        help_text="The user who purchased the subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription_term",
                    models.ForeignKey(
                        help_text="The subscription term that was purchased",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_orders",
                        to="subscriptions.subscriptionterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription order",
                "verbose_name_plural": "Subscription orders",
                "ordering": ("-date_created",),
            },
        ),
    ]
