# Generated by Django 4.2.4 on 2023-11-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0010_alter_subscriptionterm_options_subscriptionorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionorder",
            name="purchase_status",
            field=models.CharField(
                choices=[
                    ("checkout_cancelled", "Checkout cancelled"),
                    ("subscription_cancelled", "Subscription cancelled"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                help_text="Purchase status",
                max_length=50,
            ),
        ),
    ]
