# Generated by Django 4.2.4 on 2023-11-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0011_alter_subscriptionorder_purchase_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionorder",
            name="date_payment_failed",
            field=models.DateTimeField(
                blank=True, help_text="Date the payment failed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionorder",
            name="purchase_status",
            field=models.CharField(
                choices=[
                    ("checkout_cancelled", "Checkout cancelled"),
                    ("subscription_cancelled", "Subscription cancelled"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("payment_failed", "Payment failed"),
                    ("refunded", "Refunded"),
                ],
                help_text="Purchase status",
                max_length=50,
            ),
        ),
    ]
