# Generated by Django 4.2.4 on 2023-11-08 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0012_subscriptionorder_date_payment_failed_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubscriptionTerm",
            new_name="SubscriptionPeriod",
        ),
        migrations.RenameField(
            model_name="subscriptionorder",
            old_name="date_end",
            new_name="current_period_end_date",
        ),
        migrations.RenameField(
            model_name="subscriptionorder",
            old_name="date_start",
            new_name="current_period_start_date",
        ),
        migrations.RemoveField(
            model_name="subscriptionorder",
            name="subscription_term",
        ),
        migrations.AddField(
            model_name="subscriptionorder",
            name="subscription_period",
            field=models.ForeignKey(
                help_text="The subscription period that was purchased",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_orders",
                to="subscriptions.subscriptionperiod",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionorder",
            name="purchase_status",
            field=models.CharField(
                choices=[
                    ("checkout_cancelled", "Checkout cancelled"),
                    ("error", "Error"),
                    ("paid", "Paid"),
                    ("payment_failed", "Payment failed"),
                    ("pending", "Pending"),
                    ("refunded", "Refunded"),
                    ("subscription_cancelled", "Subscription cancelled"),
                ],
                help_text="Purchase status",
                max_length=50,
            ),
        ),
    ]
