# Generated by Django 4.2.4 on 2023-11-08 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0013_rename_subscriptionterm_subscriptionperiod_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionperiod",
            options={
                "ordering": ("price_cents",),
                "verbose_name": "Subscription period",
                "verbose_name_plural": "Subscription periods",
            },
        ),
    ]
