# Generated by Django 4.2.4 on 2023-11-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0014_alter_subscriptionperiod_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionorder",
            name="current_period_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when the subscription period started",
                null=True,
            ),
        ),
    ]
