# Generated by Django 4.2.4 on 2023-11-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0015_alter_subscriptionorder_current_period_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionorder",
            name="date_renewal",
        ),
        migrations.AddField(
            model_name="subscriptionorder",
            name="date_ended",
            field=models.DateTimeField(
                blank=True, help_text="Date the subscription ended", null=True
            ),
        ),
    ]
