# Generated by Django 4.2.4 on 2023-11-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0016_remove_subscriptionorder_date_renewal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionorder",
            name="purchase_status",
        ),
        migrations.AddField(
            model_name="subscriptionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("checkout_cancelled", "Checkout cancelled"),
                    ("error", "Error"),
                    ("past_due", "Past due"),
                    ("payment_failed", "Payment failed"),
                    ("processing", "Processing"),
                ],
                default="active",
                help_text="Purchase status",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
