# Generated by Django 4.2.4 on 2023-11-11 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0017_remove_subscriptionorder_purchase_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionperiod",
            options={
                "ordering": ("-price_cents",),
                "verbose_name": "Subscription period",
                "verbose_name_plural": "Subscription periods",
            },
        ),
    ]
