# Generated by Django 4.2.4 on 2023-11-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0018_alter_subscriptionperiod_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionorder",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="If true, this subscription order is active"
            ),
        ),
    ]
