# Generated by Django 4.2.4 on 2023-11-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0019_alter_subscriptionorder_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionorder",
            name="stripe_json_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stripe data at the time of the order",
                null=True,
                verbose_name="Stripe data",
            ),
        ),
    ]
