# Generated by Django 4.2.4 on 2023-11-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0020_subscriptionorder_stripe_json_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionorder",
            name="cancel_at_period_end",
            field=models.BooleanField(
                default=False,
                help_text="If true, the subscription will be cancelled at the end of                                               the current period",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionorder",
            name="date_cancelled",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the subscription was cancelled by the user",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionorder",
            name="date_ended",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the subscription was/will be ended",
                null=True,
            ),
        ),
    ]
