# Generated by Django 4.2.2 on 2023-08-21 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the individual providing feedback",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "page_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the page where feedback was provided",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                            ("general", "General Feedback"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Category of the feedback",
                        max_length=55,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Content of the feedback",
                        max_length=3000,
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the feedback",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the feedback was created",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the feedback was last modified",
                        verbose_name="Date modified",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that provided feedback",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
