# Generated by Django 4.2.4 on 2023-10-19 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
            },
        ),
        migrations.AlterField(
            model_name="feedback",
            name="category",
            field=models.CharField(
                choices=[
                    ("bug", "Bug Report"),
                    ("feature", "Feature Request"),
                    ("general", "General Feedback"),
                    ("other", "Other"),
                ],
                default="general",
                help_text="Category of the feedback",
                max_length=55,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Content of the feedback",
                max_length=3000,
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email of the individual providing feedback",
                max_length=255,
                null=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="is_processed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the feedback has been processed or not",
                verbose_name="Is processed",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the individual providing feedback",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="page_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the page where feedback was provided",
                max_length=255,
                null=True,
                verbose_name="Page URL",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that provided feedback",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
