# Generated by Django 4.2.2 on 2023-08-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email of the individual providing feedback",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="is_processed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the feedback has been processed or not",
            ),
        ),
    ]
