# Generated by Django 4.2.4 on 2023-08-26 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0002_feedback_email_feedback_is_processed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
            },
        ),
        migrations.AlterField(
            model_name="feedback",
            name="category",
            field=models.CharField(
                choices=[
                    ("bug", "Bug Report"),
                    ("feature", "Feature Request"),
                    ("general", "General Feedback"),
                    ("other", "Other"),
                ],
                default="general",
                help_text="Category of the feedback",
                max_length=55,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that provided feedback",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
