# Generated by Django 4.2.4 on 2023-09-17 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_alter_feedback_options_alter_feedback_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Feedback", "verbose_name_plural": "Feedback"},
        ),
    ]
