# Generated by Django 4.2.4 on 2023-11-02 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_alter_feedback_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the item",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
