# Generated by Django 4.2.4 on 2023-09-17 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0004_alter_feedback_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
            },
        ),
    ]
