# Generated by Django 4.2.4 on 2023-10-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="session_data_beforeunload",
            field=models.JSONField(
                blank=True, help_text="Session data beforeunload", null=True
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="session_data_onload",
            field=models.JSONField(
                blank=True, help_text="Session data onload", null=True
            ),
        ),
    ]
