# Generated by Django 4.2.4 on 2023-10-23 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_usersession_session_data_beforeunload_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objectviewed",
            options={
                "ordering": ["-date_viewed"],
                "verbose_name": "Object viewed",
                "verbose_name_plural": "Objects viewed",
            },
        ),
        migrations.RenameField(
            model_name="objectviewed",
            old_name="timestamp",
            new_name="date_viewed",
        ),
    ]
