# Generated by Django 4.2.3 on 2023-10-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_objectviewed_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="URLModelMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_pattern",
                    models.CharField(
                        help_text="Pattern of the URL, e.g., '/blog/posts/'",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "app_name",
                    models.CharField(help_text="App name, e.g., 'blog'", max_length=50),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model name, e.g., 'post'", max_length=50
                    ),
                ),
            ],
            options={
                "unique_together": {("app_name", "model_name")},
            },
        ),
    ]
