# Generated by Django 4.2.3 on 2023-10-13 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_urlmodelmap"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="urlmodelmap",
            name="url_pattern",
        ),
        migrations.AddField(
            model_name="urlmodelmap",
            name="url_name",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Name of the URL, e.g., 'post'",
                max_length=200,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
