# Generated by Django 4.2.4 on 2023-10-23 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_alter_objectviewed_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectviewed",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the object_viewed",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
