# Generated by Django 4.2.4 on 2023-10-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_objectviewed_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersession",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "User session",
                "verbose_name_plural": "User sessions",
            },
        ),
        migrations.AddField(
            model_name="usersession",
            name="date_session_ended",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Server date and time when the session ended",
                verbose_name="Date session ended",
            ),
        ),
    ]
