# Generated by Django 4.2.3 on 2023-10-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_remove_urlmodelmap_url_pattern_urlmodelmap_url_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="urlmodelmap",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="urlmodelmap",
            name="namespace",
            field=models.CharField(
                blank=True,
                help_text="URL namespace, e.g., 'blog'",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="urlmodelmap",
            name="url_name",
            field=models.CharField(
                help_text="Name of the URL without namespace, e.g., 'post'",
                max_length=200,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="urlmodelmap",
            unique_together={("namespace", "url_name")},
        ),
    ]
