# Generated by Django 4.2.3 on 2023-10-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_alter_urlmodelmap_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="urlmodelmap",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="urlmodelmap",
            name="namespace1",
            field=models.CharField(
                blank=True,
                help_text="URL namespace, e.g., 'blog'",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="urlmodelmap",
            unique_together={("namespace1", "url_name")},
        ),
        migrations.RemoveField(
            model_name="urlmodelmap",
            name="namespace",
        ),
    ]
