# Generated by Django 4.2.5 on 2023-10-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("analytics", "0006_usersession_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectviewed",
            name="content_type",
            field=models.ForeignKey(
                help_text="Content type",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_viewed",
                to="contenttypes.contenttype",
                verbose_name="Content type",
            ),
        ),
        migrations.AlterField(
            model_name="objectviewed",
            name="user_session",
            field=models.ForeignKey(
                blank=True,
                help_text="User session that the object was viewed in",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="object_viewed",
                to="analytics.usersession",
                verbose_name="User session",
            ),
        ),
    ]
