# Generated by Django 4.2.5 on 2023-10-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("analytics", "0007_alter_objectviewed_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectviewed",
            name="content_type",
            field=models.ForeignKey(
                help_text="Content type",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Content type",
            ),
        ),
    ]
