# Generated by Django 4.2.3 on 2023-10-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_alter_urlmodelmap_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="URLModelMap",
        ),
    ]
